### PR TITLE
Trim Bootstrap

### PR DESCRIPTION
**Pull request by matthew-white**
See #37.

### CODE REVIEW

**Comment by clint-tseng** [comment]
Did you do this manually? How do we replicate for future versions?

**Comment by matthew-white** [comment]
Yes, all the removal was manual (though didn't take long). The current version of Bootstrap is v4, but we're using the latest version of v3: I believe v4 was still alpha when we got started. There are some big changes from v3 to v4, so I'd guess that we'll probably want to hold off on moving to v4 for a while, and once we do, we'll probably have to redo some of these removals.

**Comment by clint-tseng** [comment]
:/ they don't have like a builder of some kind? the old jquery ui stuffs had a builder you could go and check the things you wanted and it would build you just that file. and then it also would leave a comment in that file that the builder understood so you could just feed it back in and it would give you the equivalent of the latest version.

**Comment by matthew-white** [comment]
That does sound nice. I don't see anything official along those lines. I could try to see whether third-party options exists. I do also think that v3 will last us for a good while. How about we revisit this question once we start thinking about updating to v4?

**Pull request merged**
